version: "3.7"
services:
  app:
    build: .
    ports:
      - "7777:80"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://icefusion:1qa2ws3e@development.qcknamf.mongodb.net/ampere?retryWrites=true&w=majority
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432

  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql
    tty: true
    volumes:
    - pg-data:/pg-data

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - PGDATA=/pg-data
    ports:
      - 5432:5432
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  pg-data: